import { UltraHonkBackend, type BackendOptions, type ProofData } from '@aztec/bb.js';
import type { CompiledCircuit } from '@noir-lang/types';
import { Noir } from '@noir-lang/noir_js';
import type { CredentialProof, ProofAdapter, ProofRequest, ProofResult, VerifierResult } from '@0xagentio/core';
import { validateActionAgainstPolicy, validateCredentialForPolicy } from '@0xagentio/core';
import type { AuthorizationCircuitArtifact } from './artifact.js';
import { loadAuthorizationCircuitArtifact } from './artifact.js';
import { buildAuthorizationCircuitInput, hashToField } from './witness.js';
import {
  decodeNoirAuthorizationProof,
  encodeNoirAuthorizationProof,
  NOIR_AUTHORIZATION_PROOF_FORMAT,
} from './proof-format.js';

/** Options for the real Noir proof adapter. */
export type NoirProofAdapterOptions = {
  /**
   * Stable identifier for the authorization circuit this adapter proves with.
   *
   * Developers and peer agents need this id to reject proofs generated for the
   * wrong circuit version instead of trusting any Noir-shaped payload.
   */
  readonly circuitId?: string;
  /** Preloaded compiled circuit artifact. Useful for tests and bundled apps. */
  readonly artifact?: AuthorizationCircuitArtifact;
  /** Path to the compiled circuit artifact generated by `nargo compile`. */
  readonly artifactPath?: string;
  /** Optional Barretenberg backend options for advanced runtime tuning. */
  readonly backendOptions?: BackendOptions;
  /** Optional Barretenberg circuit options for advanced runtime tuning. */
  readonly circuitOptions?: { readonly recursive: boolean };
};

const DEFAULT_CIRCUIT_ID = 'agentio-authorization-v0';

/**
 * Creates the real Noir-backed proof adapter for agent authorization proofs.
 *
 * The SDK consumes only the generic ProofAdapter interface, so this adapter is a
 * drop-in replacement for localNoirProofs() when an app wants real NoirJS and
 * Barretenberg proofs. Keeping it in @0xagentio/noir prevents heavy ZK
 * dependencies from becoming mandatory for every SDK user.
 */
export function noirProofs(options: NoirProofAdapterOptions = {}): ProofAdapter {
  return new NoirProofAdapter(options);
}

class NoirProofAdapter implements ProofAdapter {
  readonly #circuitId: string;
  readonly #artifact?: AuthorizationCircuitArtifact;
  readonly #artifactPath?: string;
  readonly #backendOptions?: BackendOptions;
  readonly #circuitOptions?: { readonly recursive: boolean };

  constructor(options: NoirProofAdapterOptions) {
    this.#circuitId = options.circuitId ?? DEFAULT_CIRCUIT_ID;
    this.#artifact = options.artifact;
    this.#artifactPath = options.artifactPath;
    this.#backendOptions = options.backendOptions;
    this.#circuitOptions = options.circuitOptions;
  }

  async proveAction(request: ProofRequest): Promise<ProofResult> {
    const credentialValidation = validateCredentialForPolicy(request.credential, request.policy, request.now);
    if (!credentialValidation.valid) {
      throw new Error(
        `Cannot create Noir proof for invalid credential: ${credentialValidation.issues.map((issue) => issue.code).join(', ')}`,
      );
    }

    const actionValidation = validateActionAgainstPolicy(request.policy, request.action, request.now);
    if (!actionValidation.valid) {
      throw new Error(`Cannot create Noir proof for invalid action: ${actionValidation.issues.map((issue) => issue.code).join(', ')}`);
    }

    const artifact = await this.#loadArtifact();
    const input = buildAuthorizationCircuitInput(request);
    const noir = new Noir(artifact as CompiledCircuit);
    const backend = new UltraHonkBackend(artifact.bytecode, this.#backendOptions, this.#circuitOptions);

    try {
      const { witness } = await noir.execute(input);
      const proofData = await backend.generateProof(witness);

      return {
        proof: {
          format: NOIR_AUTHORIZATION_PROOF_FORMAT,
          proof: encodeNoirAuthorizationProof(this.#circuitId, proofData),
          publicInputs: {
            agentId: request.credential.agentId,
            policyHash: request.credential.policyHash,
            actionType: request.action.type,
          },
        },
      };
    } finally {
      await backend.destroy();
    }
  }

  async verifyProof(proof: CredentialProof): Promise<VerifierResult> {
    if (proof.format !== NOIR_AUTHORIZATION_PROOF_FORMAT) {
      return { valid: false, reason: `Unsupported proof format ${proof.format}.` };
    }

    let decoded: ReturnType<typeof decodeNoirAuthorizationProof>;
    try {
      decoded = decodeNoirAuthorizationProof(proof.proof);
      this.#assertProofPublicInputsMatch(proof, decoded.noirPublicInputs);
    } catch (error) {
      return { valid: false, reason: error instanceof Error ? error.message : 'Invalid Noir authorization proof payload.' };
    }

    if (decoded.circuitId !== this.#circuitId) {
      return { valid: false, reason: `Unexpected circuit id ${decoded.circuitId}.` };
    }

    const artifact = await this.#loadArtifact();
    const backend = new UltraHonkBackend(artifact.bytecode, this.#backendOptions, this.#circuitOptions);

    try {
      const valid = await backend.verifyProof(decoded.proofData as ProofData);
      return { valid, reason: valid ? undefined : 'Barretenberg proof verification failed.' };
    } finally {
      await backend.destroy();
    }
  }

  async #loadArtifact(): Promise<AuthorizationCircuitArtifact> {
    return this.#artifact ?? loadAuthorizationCircuitArtifact(this.#artifactPath);
  }

  #assertProofPublicInputsMatch(proof: CredentialProof, noirPublicInputs: readonly string[]): void {
    const agentId = proof.publicInputs.agentId;
    const policyHash = proof.publicInputs.policyHash;
    const actionType = proof.publicInputs.actionType;

    if (typeof agentId !== 'string' || typeof policyHash !== 'string' || typeof actionType !== 'string') {
      throw new TypeError('Noir proof public inputs must include string agentId, policyHash, and actionType.');
    }

    assertFieldEquals(noirPublicInputs[0], hashToField(agentId), 'agentId');
    assertFieldEquals(noirPublicInputs[1], hashToField(policyHash), 'policyHash');
    assertFieldEquals(noirPublicInputs[2], hashToField(actionType), 'actionType');
  }
}

function assertFieldEquals(actual: string | undefined, expected: string, label: string): void {
  if (actual === undefined) {
    throw new TypeError(`Noir proof is missing public input for ${label}.`);
  }

  if (BigInt(actual) !== BigInt(expected)) {
    throw new TypeError(`Noir proof public input mismatch for ${label}.`);
  }
}
